[package]
name = "graphrs"
version = "0.1.0"
authors = ["Malcolm van Raalte <malcolm@van.raalte.ca>"]
description = "GraphRS is a Rust package for the creation, manipulation and analysis of graphs."
edition = "2018"
license = "MIT"
homepage = "https://github.com/malcolmvr/graphrs"
repository = "https://github.com/malcolmvr/graphrs"
readme = "README.md"
keywords = ["graph", "network", "network analysis", "nodes", "edges", "vertex", "vertices", "directed", "undirected", "acyclic", "multigraph", "graph theory", "weighted graph", "social network analysis"]
categories = ["data-structures", "algorithms", "mathematics", "science"]
exclude = [".vscode/*", "tests/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
serde = { version = "1.0", optional = true, features = ["derive"] }