[package]
name = "graphrs"
version = "0.1.0"
authors = ["Malcolm van Raalte <malcolm@gainx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
serde = { version = "1.0", optional = true, features = ["derive"] }